# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 17:55
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='N\xfamero')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('cp', models.CharField(max_length=20, verbose_name='C.P.')),
                ('rfc', models.CharField(max_length=20, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel\xe9fono')),
                ('telefono_dos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel\xe9fono No.2')),
                ('email', models.CharField(max_length=60, verbose_name='Correo Electr\xf3nico')),
                ('last_edit_date', models.DateTimeField(auto_now_add=True)),
                ('estado', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Pais', verbose_name='Pa\xeds')),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='N\xfamero')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('cp', models.CharField(max_length=20, verbose_name='C.P.')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel\xe9fono')),
                ('latitud', models.FloatField(blank=True, default=0, null=True)),
                ('longitud', models.FloatField(blank=True, default=0, null=True)),
                ('last_edit_date', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cliente', verbose_name='Pa\xeds')),
                ('estado', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Pais', verbose_name='Pa\xeds')),
            ],
            options={
                'verbose_name_plural': 'Direcci\xf3n de entrega',
            },
        ),
    ]
