# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-05 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agujeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Agujeta')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Corte')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Estilo')),
                ('imagen', models.FileField(upload_to='media/estilos/', verbose_name='Foto')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Forro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Forro')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_de', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Este campo debe contener numeros', regex='^[0-9]*$')], verbose_name='De')),
                ('linea_a', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Este campo debe contener numeros', regex='^[0-9]*$')], verbose_name='A')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Ojillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Ojillo')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Suela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z]*$')], verbose_name='Suela')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
