# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_agujeta_corte_estilo_forro_linea_ojillo_suela'),
        ('catalogos', '0003_auto_20180506_1819'),
    ]

    operations = [
    ]
