# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 16:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_merge_20180507_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Color')),
                ('RGB', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Este campo es alfanum\xe9rico', regex='^[a-zA-Z0-9]*$')], verbose_name='Color RGB')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='ParesPorPunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros', regex='^[0-9]*$')], verbose_name='Talla')),
                ('total_pares', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros', regex='^[0-9]*$')], verbose_name='Total de Pares')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Linea')),
            ],
        ),
        migrations.AlterField(
            model_name='agujeta',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Agujeta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='forro',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Forro'),
        ),
        migrations.AlterField(
            model_name='ojillo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Ojillo'),
        ),
        migrations.AlterField(
            model_name='suela',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener numeros', regex='^[a-zA-Z ]*$')], verbose_name='Suela'),
        ),
    ]
