# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_auto_20180507_1618'),
        ('catalogos', '0005_auto_20180507_1647'),
    ]

    operations = [
    ]
