# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20180610_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='codigo',
            field=models.TextField(blank=True, max_length=3, verbose_name='C\xf3digo'),
        ),
    ]
