# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_auto_20180622_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener letras', regex='^[0-9]*$')], verbose_name='C\xf3digo'),
        ),
    ]
