# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 01:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_auto_20180622_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suela',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo no debe contener caracteres especiales', regex='^[a-zA-Z0-9 ]*$')], verbose_name='Suela'),
        ),
    ]
