# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 14:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0006_auto_20180610_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero de Lote')),
                ('observaciones', models.TextField(blank=True, max_length=600, verbose_name='Observaciones')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('fecha_genera', models.DateField(verbose_name='Fecha de creacion')),
                ('programa', models.IntegerField(default=0, verbose_name='Programa')),
                ('agujeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Agujeta', verbose_name='Agujeta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cliente', verbose_name='Cliente')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Color', verbose_name='Color')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Corte', verbose_name='Corte')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estilo', verbose_name='Estilo')),
                ('forro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Forro', verbose_name='Forro')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Linea', verbose_name='Linea')),
                ('ojillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Ojillo', verbose_name='Ojillo')),
                ('suela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Suela', verbose_name='Suela')),
                ('usuario_genera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Genera')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='ParesPorPunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta numeros', regex='^[0-9]*$')], verbose_name='Talla')),
                ('total_pares', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta numeros', regex='^[0-9]*$')], verbose_name='Total de Pares')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Lote')),
            ],
        ),
    ]
