# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 04:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20180610_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=600, verbose_name='Descripcion')),
                ('fecha_genera', models.DateField(verbose_name='Fecha de creacion')),
                ('agujeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Agujeta', verbose_name='Agujeta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cliente', verbose_name='Cliente')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Color', verbose_name='Color')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Corte', verbose_name='Corte')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estilo', verbose_name='Estilo')),
                ('forro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Forro', verbose_name='Forro')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Linea', verbose_name='Linea')),
                ('ojillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Ojillo', verbose_name='Ojillo')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ParesPorPuntoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta numeros', regex='^[0-9]*$')], verbose_name='Talla')),
                ('total_pares', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Este campo solo acepta numeros', regex='^[0-9]*$')], verbose_name='Total de Pares')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.DetallePedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(default=0, verbose_name='Folio')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('observaciones', models.TextField(blank=True, max_length=600, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='suela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Suela', verbose_name='Suela'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='usuario_genera',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallepedido_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Genera'),
        ),
    ]
