# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20180619_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='fecha_genera',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
