# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20180623_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='usuario_genera',
        ),
    ]
