# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='', max_length=20, unique=True, verbose_name='Clave del Art\xedculo')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del art\xedculo')),
                ('cantidad', models.FloatField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Precio')),
                ('stock_minimo', models.FloatField(blank=True, default=0, null=True, verbose_name='Stock M\xednimo')),
            ],
            options={
                'verbose_name': 'Art\xedculo',
                'verbose_name_plural': 'Art\xedculos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Categor\xeda')),
            ],
            options={
                'verbose_name': 'Categor\xeda',
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
        migrations.CreateModel(
            name='EstatusArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Medida')),
                ('abreviatura', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Medida Abreviado')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.CategoriaArticulo', verbose_name='Categor\xeda'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.EstatusArticulo', verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
    ]
