# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Cantidad Pedida')),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Cantidad Entregada')),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Costo de Compra')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='IVA')),
                ('unidad_medida_compra', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Unidad de Medida de Compra')),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Descripci\xf3n de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default='', max_length=30, unique=True, verbose_name='F\xf3lio')),
                ('fecha_oc', models.DateField(verbose_name='Fecha de Orden de Compra')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('factura', models.CharField(max_length=50, verbose_name='Factura')),
                ('lugar_entrega', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lugar de Entrega')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Proveedor', verbose_name='Proveedor')),
                ('usuario_genera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordencompra_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Genera')),
                ('usuario_recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordencompra_requests_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Recibe')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Orden de Compra',
            },
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Art\xedculo'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Articulo', verbose_name='Articulo'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='ordencompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.OrdenCompra', verbose_name='Orden de Compra'),
        ),
    ]
