# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20171102_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'verbose_name': 'Detalle de Orden de Compra', 'verbose_name_plural': 'Detalle de Orden de Compra'},
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='numero_unidades',
            field=models.CommaSeparatedIntegerField(default=0, max_length=20, verbose_name='N\xfamero de Unidades'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='unidad_medida_compra',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Unidad de Medida de Compra'),
        ),
    ]
