# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20171102_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.EstatusArticulo', verbose_name='Estatus'),
        ),
    ]
