# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0004_auto_20171102_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Cantidad Entregada')),
            ],
            options={
                'verbose_name': 'Recepci\xf3n de Orden de Compra',
                'verbose_name_plural': 'Recepci\xf3n de Orden de Compra',
            },
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario_recibe',
        ),
        migrations.AddField(
            model_name='recepcionordencompra',
            name='ordencompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.OrdenCompra', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='recepcionordencompra',
            name='usuario_recibe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionordencompra_requests_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Recibe'),
        ),
    ]
