# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 05:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_recepcionordencompra_detalleordencopra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='numero_unidades',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='N\xfamero de Unidades'),
        ),
    ]
